import { pick } from "./locale";

/**
 * Interface strings for the chatbot and the news page.
 *
 * These lived as hardcoded Arabic inside their components, so they leaked
 * untranslated into the English, French, Portuguese and Spanish builds.
 */

export const CHATBOT = pick({
  en: {
    title: "eMa Assistant",
    clear: "Clear chat",
    minimize: "Minimise",
    open: "Open chat",
    close: "Close chat",
    greeting: "Hi! I'm your eMa assistant.",
    greetingSub: "How can I help you today?",
    thinking: "Thinking…",
    placeholder: "Ask me anything about eMa…",
    askIntro: "What would you like to know?",
    suggestions: "I'm not certain I understood. Did you mean one of these?",
    noMatch: "I don't have that in my notes about eMa — but a person can help.",
    related: "You might also ask",
    chips: {
      modules: "Find the right module",
      pricing: "Pricing & fees",
      security: "Is my money safe?",
      start: "How do I get started?",
      contact: "Talk to a person",
      back: "Back",
    },
    labels: {
      fee: "Fee",
      steps: "How it works",
      app: "Get the app",
      site: "Visit site",
      problem: "The problem",
      setup: "The setup",
      outcome: "The outcome",
      trade: "Pick your trade",
      modules: "Choose a module",
    },
  },
  ar: {
    title: "مساعد eMa",
    clear: "مسح الدردشة",
    minimize: "تصغير",
    open: "فتح الدردشة",
    close: "إغلاق الدردشة",
    greeting: "مرحباً! أنا مساعد eMa الخاص بك.",
    greetingSub: "كيف يمكنني مساعدتك اليوم؟",
    thinking: "جاري التفكير...",
    placeholder: "اسألني أي شيء عن eMa...",
    askIntro: "ما الذي تودّ معرفته؟",
    suggestions: "لستُ متأكداً أنني فهمت. هل تقصد أحد هذه؟",
    noMatch: "لا أجد هذا ضمن ما أعرفه عن eMa — لكن يمكن لأحد الزملاء مساعدتك.",
    related: "قد تسأل أيضاً",
    chips: {
      modules: "اعثر على الوحدة المناسبة",
      pricing: "الأسعار والرسوم",
      security: "هل أموالي آمنة؟",
      start: "كيف أبدأ؟",
      contact: "التحدث مع شخص",
      back: "رجوع",
    },
    labels: {
      fee: "الرسوم",
      steps: "كيف تعمل",
      app: "حمّل التطبيق",
      site: "زيارة الموقع",
      problem: "المشكلة",
      setup: "الإعداد",
      outcome: "النتيجة",
      trade: "اختر مجالك",
      modules: "اختر وحدة",
    },
  },
  fr: {
    title: "Assistant eMa",
    clear: "Effacer la conversation",
    minimize: "Réduire",
    open: "Ouvrir la conversation",
    close: "Fermer la conversation",
    greeting: "Bonjour ! Je suis votre assistant eMa.",
    greetingSub: "Comment puis-je vous aider aujourd'hui ?",
    thinking: "Réflexion en cours…",
    placeholder: "Posez-moi une question sur eMa…",
    askIntro: "Que souhaitez-vous savoir ?",
    suggestions: "Je ne suis pas sûr d'avoir compris. Vouliez-vous dire :",
    noMatch: "Je n'ai pas cela dans ce que je sais d'eMa — mais une personne peut vous aider.",
    related: "Vous pourriez aussi demander",
    chips: {
      modules: "Trouver le bon module",
      pricing: "Tarifs et frais",
      security: "Mon argent est-il en sécurité ?",
      start: "Comment commencer ?",
      contact: "Parler à quelqu'un",
      back: "Retour",
    },
    labels: {
      fee: "Frais",
      steps: "Comment ça marche",
      app: "Télécharger l'app",
      site: "Voir le site",
      problem: "Le problème",
      setup: "La configuration",
      outcome: "Le résultat",
      trade: "Choisissez votre métier",
      modules: "Choisir un module",
    },
  },
  pt: {
    title: "Assistente eMa",
    clear: "Limpar conversa",
    minimize: "Minimizar",
    open: "Abrir conversa",
    close: "Fechar conversa",
    greeting: "Olá! Sou o seu assistente eMa.",
    greetingSub: "Como posso ajudar hoje?",
    thinking: "A pensar…",
    placeholder: "Pergunte-me o que quiser sobre o eMa…",
    askIntro: "O que gostaria de saber?",
    suggestions: "Não tenho a certeza de ter percebido. Queria dizer:",
    noMatch: "Não tenho isso no que sei sobre o eMa — mas uma pessoa pode ajudar.",
    related: "Também pode perguntar",
    chips: {
      modules: "Encontrar o módulo certo",
      pricing: "Preços e taxas",
      security: "O meu dinheiro está seguro?",
      start: "Como começo?",
      contact: "Falar com uma pessoa",
      back: "Voltar",
    },
    labels: {
      fee: "Taxa",
      steps: "Como funciona",
      app: "Obter a app",
      site: "Ver o site",
      problem: "O problema",
      setup: "A configuração",
      outcome: "O resultado",
      trade: "Escolha o seu setor",
      modules: "Escolher um módulo",
    },
  },
  es: {
    title: "Asistente eMa",
    clear: "Borrar la conversación",
    minimize: "Minimizar",
    open: "Abrir la conversación",
    close: "Cerrar la conversación",
    greeting: "¡Hola! Soy tu asistente de eMa.",
    greetingSub: "¿En qué puedo ayudarte hoy?",
    thinking: "Pensando…",
    placeholder: "Pregúntame lo que quieras sobre eMa…",
    askIntro: "¿Qué te gustaría saber?",
    suggestions: "No estoy seguro de haber entendido. ¿Querías decir:",
    noMatch: "No tengo eso en lo que sé sobre eMa — pero una persona puede ayudarte.",
    related: "También puedes preguntar",
    chips: {
      modules: "Encontrar el módulo adecuado",
      pricing: "Precios y comisiones",
      security: "¿Está seguro mi dinero?",
      start: "¿Cómo empiezo?",
      contact: "Hablar con una persona",
      back: "Atrás",
    },
    labels: {
      fee: "Comisión",
      steps: "Cómo funciona",
      app: "Descargar la app",
      site: "Ver el sitio",
      problem: "El problema",
      setup: "La configuración",
      outcome: "El resultado",
      trade: "Elige tu sector",
      modules: "Elegir un módulo",
    },
  },
});

export const NEWS = pick({
  en: {
    loading: "Loading the latest posts…",
    errorTitle: "Couldn't load the posts",
    errorBody: "Something went wrong while fetching the news.",
    retry: "Try again",
    title: "Latest news and updates",
    subtitle:
      "Keep up with our latest posts, insights and community discussions.",
    emptyTitle: "No posts yet",
    emptyBody: "Check back later for new content.",
    namePlaceholder: "Your name",
    commentPlaceholder: "Write your comment…",
    post: "Post",
    loadingComments: "Loading comments…",
    comments: "Comments",
    noComments: "No comments yet. Be the first to comment!",
  },
  ar: {
    loading: "جاري تحميل أحدث المنشورات...",
    errorTitle: "تعذر تحميل المنشورات",
    errorBody: "حدث خطأ أثناء جلب الأخبار.",
    retry: "حاول مرة أخرى",
    title: "آخر الأخبار والتحديثات",
    subtitle: "ابق على اطلاع بأحدث منشوراتنا ورؤانا ومناقشات المجتمع",
    emptyTitle: "لا توجد منشورات بعد",
    emptyBody: "تحقق مرة أخرى لاحقًا للحصول على محتوى جديد!",
    namePlaceholder: "اسمك",
    commentPlaceholder: "اكتب تعليقك...",
    post: "نشر",
    loadingComments: "جاري تحميل التعليقات...",
    comments: "التعليقات",
    noComments: "لا توجد تعليقات بعد. كن أول من يعلق!",
  },
  fr: {
    loading: "Chargement des derniers articles…",
    errorTitle: "Impossible de charger les articles",
    errorBody: "Une erreur est survenue lors de la récupération des actualités.",
    retry: "Réessayer",
    title: "Actualités et nouveautés",
    subtitle:
      "Suivez nos derniers articles, analyses et discussions de la communauté.",
    emptyTitle: "Aucun article pour le moment",
    emptyBody: "Revenez plus tard pour découvrir du nouveau contenu.",
    namePlaceholder: "Votre nom",
    commentPlaceholder: "Écrivez votre commentaire…",
    post: "Publier",
    loadingComments: "Chargement des commentaires…",
    comments: "Commentaires",
    noComments: "Aucun commentaire pour l'instant. Soyez le premier !",
  },
  pt: {
    loading: "A carregar as publicações mais recentes…",
    errorTitle: "Não foi possível carregar as publicações",
    errorBody: "Ocorreu um erro ao obter as notícias.",
    retry: "Tentar novamente",
    title: "Notícias e novidades",
    subtitle:
      "Acompanhe as nossas publicações, análises e discussões da comunidade.",
    emptyTitle: "Ainda não há publicações",
    emptyBody: "Volte mais tarde para ver novos conteúdos.",
    namePlaceholder: "O seu nome",
    commentPlaceholder: "Escreva o seu comentário…",
    post: "Publicar",
    loadingComments: "A carregar comentários…",
    comments: "Comentários",
    noComments: "Ainda não há comentários. Seja o primeiro!",
  },
  es: {
    loading: "Cargando las publicaciones más recientes…",
    errorTitle: "No se han podido cargar las publicaciones",
    errorBody: "Ha ocurrido un error al obtener las noticias.",
    retry: "Reintentar",
    title: "Noticias y novedades",
    subtitle:
      "Sigue nuestras publicaciones, análisis y conversaciones de la comunidad.",
    emptyTitle: "Todavía no hay publicaciones",
    emptyBody: "Vuelve más tarde para ver contenido nuevo.",
    namePlaceholder: "Tu nombre",
    commentPlaceholder: "Escribe tu comentario…",
    post: "Publicar",
    loadingComments: "Cargando comentarios…",
    comments: "Comentarios",
    noComments: "Aún no hay comentarios. ¡Sé el primero!",
  },
});
